// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_key.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createApiKey = `-- name: CreateApiKey :one
INSERT INTO api_key (
    value
) VALUES (
    $1
)
RETURNING id, value, active, created_at, updated_at, deleted_at
`

func (q *Queries) CreateApiKey(ctx context.Context, value string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createApiKey, value)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const disableApiKey = `-- name: DisableApiKey :exec
UPDATE api_key
    SET active = false
WHERE id = $1
`

func (q *Queries) DisableApiKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableApiKey, id)
	return err
}

const enableApiKey = `-- name: EnableApiKey :exec
UPDATE api_key
    SET active = false
WHERE id = $1
`

func (q *Queries) EnableApiKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, enableApiKey, id)
	return err
}

const getApiKey = `-- name: GetApiKey :one
SELECT id, value, active, created_at, updated_at, deleted_at FROM api_key
WHERE ID = $1
`

func (q *Queries) GetApiKey(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKey, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getApiKeyByValue = `-- name: GetApiKeyByValue :one
SELECT id, value, active, created_at, updated_at, deleted_at FROM api_key
WHERE value = $1
`

func (q *Queries) GetApiKeyByValue(ctx context.Context, value string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getApiKeyByValue, value)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Value,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listApiKeys = `-- name: ListApiKeys :many
SELECT id, value, active, created_at, updated_at, deleted_at FROM api_key
ORDER BY created_at
`

func (q *Queries) ListApiKeys(ctx context.Context) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listApiKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiKey
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Value,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
