// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: committee.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createCommittee = `-- name: CreateCommittee :one
INSERT INTO committee (
    name,
    slug,
    short_name,
    description,
    color,
    image_url,
    website_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7
)
RETURNING id, name, slug, short_name, description, color, image_url, website_url, active, created_at, updated_at, deleted_at
`

type CreateCommitteeParams struct {
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	ShortName   string         `json:"short_name"`
	Description sql.NullString `json:"description"`
	Color       string         `json:"color"`
	ImageUrl    sql.NullString `json:"image_url"`
	WebsiteUrl  sql.NullString `json:"website_url"`
}

func (q *Queries) CreateCommittee(ctx context.Context, arg CreateCommitteeParams) (Committee, error) {
	row := q.db.QueryRowContext(ctx, createCommittee,
		arg.Name,
		arg.Slug,
		arg.ShortName,
		arg.Description,
		arg.Color,
		arg.ImageUrl,
		arg.WebsiteUrl,
	)
	var i Committee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCommittee = `-- name: GetCommittee :one
SELECT id, name, slug, short_name, description, color, image_url, website_url, active, created_at, updated_at, deleted_at FROM committee
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetCommittee(ctx context.Context, id uuid.UUID) (Committee, error) {
	row := q.db.QueryRowContext(ctx, getCommittee, id)
	var i Committee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommittees = `-- name: ListCommittees :many
SELECT id, name, slug, short_name, description, color, image_url, website_url, active, created_at, updated_at, deleted_at FROM committee
ORDER BY name
`

func (q *Queries) ListCommittees(ctx context.Context) ([]Committee, error) {
	rows, err := q.db.QueryContext(ctx, listCommittees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Committee
	for rows.Next() {
		var i Committee
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ShortName,
			&i.Description,
			&i.Color,
			&i.ImageUrl,
			&i.WebsiteUrl,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommittee = `-- name: UpdateCommittee :one
UPDATE committee
    SET name = $2,
    slug = $3,
    short_name = $4,
    description = $5,
    color = $6,
    image_url = $7,
    website_url = $8
WHERE ID = $1
RETURNING id, name, slug, short_name, description, color, image_url, website_url, active, created_at, updated_at, deleted_at
`

type UpdateCommitteeParams struct {
	ID          uuid.UUID      `json:"id"`
	Name        string         `json:"name"`
	Slug        string         `json:"slug"`
	ShortName   string         `json:"short_name"`
	Description sql.NullString `json:"description"`
	Color       string         `json:"color"`
	ImageUrl    sql.NullString `json:"image_url"`
	WebsiteUrl  sql.NullString `json:"website_url"`
}

func (q *Queries) UpdateCommittee(ctx context.Context, arg UpdateCommitteeParams) (Committee, error) {
	row := q.db.QueryRowContext(ctx, updateCommittee,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ShortName,
		arg.Description,
		arg.Color,
		arg.ImageUrl,
		arg.WebsiteUrl,
	)
	var i Committee
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
