// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: groups.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createGroup = `-- name: CreateGroup :one
INSERT INTO groups (
    name,
    slug,
    short_name,
    description,
    color,
    image_url,
    website_url,
    established_at,
    dissolved_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, name, slug, short_name, description, color, image_url, website_url, established_at, dissolved_at, created_at, updated_at, deleted_at
`

type CreateGroupParams struct {
	Name          string
	Slug          string
	ShortName     string
	Description   *string
	Color         string
	ImageUrl      *string
	WebsiteUrl    *string
	EstablishedAt pgtype.Date
	DissolvedAt   pgtype.Date
}

func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, createGroup,
		arg.Name,
		arg.Slug,
		arg.ShortName,
		arg.Description,
		arg.Color,
		arg.ImageUrl,
		arg.WebsiteUrl,
		arg.EstablishedAt,
		arg.DissolvedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteGroup = `-- name: DeleteGroup :one
UPDATE groups
    SET deleted_at = NOW()
WHERE ID = $1 AND deleted_at IS NULL
RETURNING id, name, slug, short_name, description, color, image_url, website_url, established_at, dissolved_at, created_at, updated_at, deleted_at
`

func (q *Queries) DeleteGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, deleteGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, slug, short_name, description, color, image_url, website_url, established_at, dissolved_at, created_at, updated_at, deleted_at FROM groups
WHERE ID = $1 AND deleted_at IS NULL AND active = TRUE LIMIT 1
`

func (q *Queries) GetGroup(ctx context.Context, id uuid.UUID) (Group, error) {
	row := q.db.QueryRow(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, slug, short_name, description, color, image_url, website_url, established_at, dissolved_at, created_at, updated_at, deleted_at FROM groups
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.Query(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Group
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.ShortName,
			&i.Description,
			&i.Color,
			&i.ImageUrl,
			&i.WebsiteUrl,
			&i.EstablishedAt,
			&i.DissolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateGroup = `-- name: UpdateGroup :one
UPDATE groups
    SET name = $2,
    slug = $3,
    short_name = $4,
    description = $5,
    color = $6,
    image_url = $7,
    website_url = $8,
    established_at = $9,
    dissolved_at = $10
WHERE ID = $1 AND deleted_at IS NULL
RETURNING id, name, slug, short_name, description, color, image_url, website_url, established_at, dissolved_at, created_at, updated_at, deleted_at
`

type UpdateGroupParams struct {
	ID            uuid.UUID
	Name          string
	Slug          string
	ShortName     string
	Description   *string
	Color         string
	ImageUrl      *string
	WebsiteUrl    *string
	EstablishedAt pgtype.Date
	DissolvedAt   pgtype.Date
}

func (q *Queries) UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error) {
	row := q.db.QueryRow(ctx, updateGroup,
		arg.ID,
		arg.Name,
		arg.Slug,
		arg.ShortName,
		arg.Description,
		arg.Color,
		arg.ImageUrl,
		arg.WebsiteUrl,
		arg.EstablishedAt,
		arg.DissolvedAt,
	)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.ShortName,
		&i.Description,
		&i.Color,
		&i.ImageUrl,
		&i.WebsiteUrl,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
