// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (
    name,
    email,
    group_id,
    established_at,
    dissolved_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, name, email, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at
`

type CreatePositionParams struct {
	Name          string
	Email         string
	GroupID       uuid.UUID
	EstablishedAt pgtype.Date
	DissolvedAt   pgtype.Date
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.Name,
		arg.Email,
		arg.GroupID,
		arg.EstablishedAt,
		arg.DissolvedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePosition = `-- name: DeletePosition :one
UPDATE positions
    SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at
`

func (q *Queries) DeletePosition(ctx context.Context, id uuid.UUID) (Position, error) {
	row := q.db.QueryRow(ctx, deletePosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, name, email, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at FROM positions
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPosition(ctx context.Context, id uuid.UUID) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPositions = `-- name: ListPositions :many
SELECT id, name, email, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at FROM positions
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.GroupID,
			&i.EstablishedAt,
			&i.DissolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
    SET name = $2,
    email = $3,
    group_id = $4,
    established_at = $5,
    dissolved_at = $6
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at
`

type UpdatePositionParams struct {
	ID            uuid.UUID
	Name          string
	Email         string
	GroupID       uuid.UUID
	EstablishedAt pgtype.Date
	DissolvedAt   pgtype.Date
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.GroupID,
		arg.EstablishedAt,
		arg.DissolvedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
