// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: positions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO positions (
    name,
    email,
    description,
    group_id,
    established_at,
    dissolved_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, name, email, description, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at
`

type CreatePositionParams struct {
	Name          string
	Email         string
	Description   *string
	GroupID       uuid.UUID
	EstablishedAt pgtype.Date
	DissolvedAt   pgtype.Date
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, createPosition,
		arg.Name,
		arg.Email,
		arg.Description,
		arg.GroupID,
		arg.EstablishedAt,
		arg.DissolvedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePosition = `-- name: DeletePosition :one
UPDATE positions
    SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, description, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at
`

func (q *Queries) DeletePosition(ctx context.Context, id uuid.UUID) (Position, error) {
	row := q.db.QueryRow(ctx, deletePosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, name, email, description, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at FROM positions
WHERE id = $1 AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPosition(ctx context.Context, id uuid.UUID) (Position, error) {
	row := q.db.QueryRow(ctx, getPosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGroupPositionsWithActiveTrustees = `-- name: ListGroupPositionsWithActiveTrustees :many
SELECT
    pos.id as position_id,
    pos.name as position_name,
    pos.email as position_email,
    pos.description as position_description,
    pos.group_id,
    pos.established_at as position_established_at,
    pos.dissolved_at as position_dissolved_at,
    t.id as trustee_id,
    t.start_date,
    t.end_date,
    u.id as user_id,
    u.first_name,
    u.last_name,
    u.image_url as user_image_url
FROM positions pos
LEFT JOIN trustees t ON t.position_id = pos.id 
    AND t.deleted_at IS NULL 
    AND (t.end_date IS NULL OR t.end_date > CURRENT_DATE)
    AND t.start_date <= CURRENT_DATE
LEFT JOIN users u ON t.user_id = u.id AND u.deleted_at IS NULL
WHERE pos.group_id = $1
    AND pos.deleted_at IS NULL
    AND (pos.dissolved_at IS NULL OR pos.dissolved_at > CURRENT_DATE)
ORDER BY pos.name ASC
`

type ListGroupPositionsWithActiveTrusteesRow struct {
	PositionID            uuid.UUID
	PositionName          string
	PositionEmail         string
	PositionDescription   *string
	GroupID               uuid.UUID
	PositionEstablishedAt pgtype.Date
	PositionDissolvedAt   pgtype.Date
	TrusteeID             pgtype.UUID
	StartDate             pgtype.Date
	EndDate               pgtype.Date
	UserID                pgtype.UUID
	FirstName             *string
	LastName              *string
	UserImageUrl          *string
}

func (q *Queries) ListGroupPositionsWithActiveTrustees(ctx context.Context, groupID uuid.UUID) ([]ListGroupPositionsWithActiveTrusteesRow, error) {
	rows, err := q.db.Query(ctx, listGroupPositionsWithActiveTrustees, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupPositionsWithActiveTrusteesRow
	for rows.Next() {
		var i ListGroupPositionsWithActiveTrusteesRow
		if err := rows.Scan(
			&i.PositionID,
			&i.PositionName,
			&i.PositionEmail,
			&i.PositionDescription,
			&i.GroupID,
			&i.PositionEstablishedAt,
			&i.PositionDissolvedAt,
			&i.TrusteeID,
			&i.StartDate,
			&i.EndDate,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.UserImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPositions = `-- name: ListPositions :many
SELECT id, name, email, description, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at FROM positions
WHERE deleted_at IS NULL
ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.Query(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Description,
			&i.GroupID,
			&i.EstablishedAt,
			&i.DissolvedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE positions
    SET name = $2,
    email = $3,
    description = $4,
    group_id = $5,
    established_at = $6,
    dissolved_at = $7
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, description, group_id, established_at, dissolved_at, created_at, updated_at, deleted_at
`

type UpdatePositionParams struct {
	ID            uuid.UUID
	Name          string
	Email         string
	Description   *string
	GroupID       uuid.UUID
	EstablishedAt pgtype.Date
	DissolvedAt   pgtype.Date
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRow(ctx, updatePosition,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.Description,
		arg.GroupID,
		arg.EstablishedAt,
		arg.DissolvedAt,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Description,
		&i.GroupID,
		&i.EstablishedAt,
		&i.DissolvedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
