// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCommittee(ctx context.Context, arg CreateCommitteeParams) (Committee, error)
	CreatePerson(ctx context.Context, arg CreatePersonParams) (Person, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	CreateTrustee(ctx context.Context, arg CreateTrusteeParams) (Trustee, error)
	DeleteCommittee(ctx context.Context, id uuid.UUID) (Committee, error)
	DeletePerson(ctx context.Context, id uuid.UUID) (Person, error)
	DeletePosition(ctx context.Context, id uuid.UUID) (Position, error)
	GetCommittee(ctx context.Context, id uuid.UUID) (Committee, error)
	GetPerson(ctx context.Context, id uuid.UUID) (Person, error)
	GetPosition(ctx context.Context, id uuid.UUID) (Position, error)
	ListCommitteeTrustees(ctx context.Context, committeeID uuid.UUID) ([]ListCommitteeTrusteesRow, error)
	ListCommittees(ctx context.Context) ([]Committee, error)
	ListPeople(ctx context.Context) ([]Person, error)
	ListPositions(ctx context.Context) ([]Position, error)
	ListTrustees(ctx context.Context) ([]ListTrusteesRow, error)
	UpdateCommittee(ctx context.Context, arg UpdateCommitteeParams) (Committee, error)
	UpdatePerson(ctx context.Context, arg UpdatePersonParams) (Person, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
}

var _ Querier = (*Queries)(nil)
