// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateGroup(ctx context.Context, arg CreateGroupParams) (Group, error)
	CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error)
	CreateTrustee(ctx context.Context, arg CreateTrusteeParams) (Trustee, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteGroup(ctx context.Context, id uuid.UUID) (Group, error)
	DeletePosition(ctx context.Context, id uuid.UUID) (Position, error)
	DeleteUser(ctx context.Context, id uuid.UUID) (User, error)
	GetGroup(ctx context.Context, id uuid.UUID) (Group, error)
	GetPosition(ctx context.Context, id uuid.UUID) (Position, error)
	GetUser(ctx context.Context, id uuid.UUID) (User, error)
	ListGroupTrustees(ctx context.Context, groupID uuid.UUID) ([]ListGroupTrusteesRow, error)
	ListGroups(ctx context.Context) ([]Group, error)
	ListPositions(ctx context.Context) ([]Position, error)
	ListTrustees(ctx context.Context) ([]ListTrusteesRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateGroup(ctx context.Context, arg UpdateGroupParams) (Group, error)
	UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
