// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trustee.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTrustee = `-- name: CreateTrustee :one
INSERT INTO trustee (
  person_id,
  position_id,
  start_date,
  end_date
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, start_date, end_date, position_id, person_id, created_at, updated_at, deleted_at
`

type CreateTrusteeParams struct {
	PersonID   uuid.UUID
	PositionID uuid.UUID
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

func (q *Queries) CreateTrustee(ctx context.Context, arg CreateTrusteeParams) (Trustee, error) {
	row := q.db.QueryRow(ctx, createTrustee,
		arg.PersonID,
		arg.PositionID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Trustee
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.PositionID,
		&i.PersonID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCommitteeTrustees = `-- name: ListCommitteeTrustees :many
SELECT
    t.id as trustee_id,
    t.start_date,
    t.end_date,
    t.created_at as trustee_created_at,
    t.updated_at as trustee_updated_at,
    p.id as person_id,
    p.first_name,
    p.last_name,
    p.image_url as person_image_url,
    pos.id as position_id,
    pos.name as position_name,
    pos.email as position_email,
    pos.active as position_active,
    pos.committee_id
FROM trustee t
INNER JOIN person p ON t.person_id = p.id
INNER JOIN position pos ON t.position_id = pos.id
WHERE pos.committee_id = $1
    AND t.deleted_at IS NULL
    AND p.deleted_at IS NULL
    AND pos.deleted_at IS NULL
ORDER BY t.start_date DESC, pos.name ASC
`

type ListCommitteeTrusteesRow struct {
	TrusteeID        uuid.UUID
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	TrusteeCreatedAt pgtype.Timestamp
	TrusteeUpdatedAt pgtype.Timestamp
	PersonID         uuid.UUID
	FirstName        string
	LastName         string
	PersonImageUrl   *string
	PositionID       uuid.UUID
	PositionName     string
	PositionEmail    string
	PositionActive   bool
	CommitteeID      uuid.UUID
}

func (q *Queries) ListCommitteeTrustees(ctx context.Context, committeeID uuid.UUID) ([]ListCommitteeTrusteesRow, error) {
	rows, err := q.db.Query(ctx, listCommitteeTrustees, committeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommitteeTrusteesRow
	for rows.Next() {
		var i ListCommitteeTrusteesRow
		if err := rows.Scan(
			&i.TrusteeID,
			&i.StartDate,
			&i.EndDate,
			&i.TrusteeCreatedAt,
			&i.TrusteeUpdatedAt,
			&i.PersonID,
			&i.FirstName,
			&i.LastName,
			&i.PersonImageUrl,
			&i.PositionID,
			&i.PositionName,
			&i.PositionEmail,
			&i.PositionActive,
			&i.CommitteeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
