// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: trustees.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTrustee = `-- name: CreateTrustee :one
INSERT INTO trustees (
  user_id,
  position_id,
  start_date,
  end_date
) VALUES (
  $1,
  $2,
  $3,
  $4
) RETURNING id, start_date, end_date, position_id, user_id, created_at, updated_at, deleted_at
`

type CreateTrusteeParams struct {
	UserID     uuid.UUID
	PositionID uuid.UUID
	StartDate  pgtype.Date
	EndDate    pgtype.Date
}

func (q *Queries) CreateTrustee(ctx context.Context, arg CreateTrusteeParams) (Trustee, error) {
	row := q.db.QueryRow(ctx, createTrustee,
		arg.UserID,
		arg.PositionID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Trustee
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.PositionID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGroupTrustees = `-- name: ListGroupTrustees :many
SELECT
    t.id as trustee_id,
    t.start_date,
    t.end_date,
    t.created_at as trustee_created_at,
    t.updated_at as trustee_updated_at,
    p.id as user_id,
    p.first_name,
    p.last_name,
    p.image_url as user_image_url,
    pos.id as position_id,
    pos.name as position_name,
    pos.email as position_email,
    pos.group_id
FROM trustees t
INNER JOIN users p ON t.user_id = p.id
INNER JOIN positions pos ON t.position_id = pos.id
WHERE pos.group_id = $1
    AND t.deleted_at IS NULL
    AND p.deleted_at IS NULL
    AND pos.deleted_at IS NULL
ORDER BY t.start_date DESC, pos.name ASC
`

type ListGroupTrusteesRow struct {
	TrusteeID        uuid.UUID
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	TrusteeCreatedAt pgtype.Timestamp
	TrusteeUpdatedAt pgtype.Timestamp
	UserID           uuid.UUID
	FirstName        string
	LastName         string
	UserImageUrl     *string
	PositionID       uuid.UUID
	PositionName     string
	PositionEmail    string
	GroupID          uuid.UUID
}

func (q *Queries) ListGroupTrustees(ctx context.Context, groupID uuid.UUID) ([]ListGroupTrusteesRow, error) {
	rows, err := q.db.Query(ctx, listGroupTrustees, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGroupTrusteesRow
	for rows.Next() {
		var i ListGroupTrusteesRow
		if err := rows.Scan(
			&i.TrusteeID,
			&i.StartDate,
			&i.EndDate,
			&i.TrusteeCreatedAt,
			&i.TrusteeUpdatedAt,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.UserImageUrl,
			&i.PositionID,
			&i.PositionName,
			&i.PositionEmail,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrustees = `-- name: ListTrustees :many
SELECT
  t.id trustee_id,
  t.start_date,
  t.end_date,
  u.id user_id,
  u.first_name,
  u.last_name,
  pos.id position_id,
  pos.name position_name,
  g.name group_name,
  g.id group_id
FROM trustees t
INNER JOIN users u ON t.user_id = u.id
INNER JOIN positions pos ON t.position_id = pos.id
INNER JOIN groups g ON pos.group_id = g.id
`

type ListTrusteesRow struct {
	TrusteeID    uuid.UUID
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	UserID       uuid.UUID
	FirstName    string
	LastName     string
	PositionID   uuid.UUID
	PositionName string
	GroupName    string
	GroupID      uuid.UUID
}

func (q *Queries) ListTrustees(ctx context.Context) ([]ListTrusteesRow, error) {
	rows, err := q.db.Query(ctx, listTrustees)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTrusteesRow
	for rows.Next() {
		var i ListTrusteesRow
		if err := rows.Scan(
			&i.TrusteeID,
			&i.StartDate,
			&i.EndDate,
			&i.UserID,
			&i.FirstName,
			&i.LastName,
			&i.PositionID,
			&i.PositionName,
			&i.GroupName,
			&i.GroupID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
