// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID        uuid.UUID
	Value     string
	Active    bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Committee struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	ShortName   string
	Description *string
	Color       string
	ImageUrl    *string
	WebsiteUrl  *string
	Active      bool
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type Person struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	ImageUrl  *string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Position struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Active      bool
	CommitteeID uuid.UUID
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
	DeletedAt   pgtype.Timestamp
}

type Trustee struct {
	ID         uuid.UUID
	StartDate  pgtype.Date
	EndDate    pgtype.Date
	PositionID uuid.UUID
	PersonID   uuid.UUID
	CreatedAt  pgtype.Timestamp
	UpdatedAt  pgtype.Timestamp
	DeletedAt  pgtype.Timestamp
}
