// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID    uuid.UUID
	Value string
}

type Committee struct {
	ID          uuid.UUID
	Name        string
	Slug        string
	ShortName   string
	Description sql.NullString
	Color       string
	ImageUrl    sql.NullString
	WebsiteUrl  sql.NullString
	Active      sql.NullBool
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Person struct {
	ID        uuid.UUID
	FirstName string
	LastName  string
	ImageUrl  sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Position struct {
	ID          uuid.UUID
	Name        string
	Email       string
	Active      sql.NullBool
	CommitteeID uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
	DeletedAt   sql.NullTime
}

type Trustee struct {
	ID         uuid.UUID
	StartDate  time.Time
	EndDate    time.Time
	PositionID uuid.UUID
	PersonID   uuid.UUID
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
	DeletedAt  sql.NullTime
}
