// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: position.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createPosition = `-- name: CreatePosition :one
INSERT INTO position (
    name,
    email,
    committee_id
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, name, email, active, committee_id, created_at, updated_at, deleted_at
`

type CreatePositionParams struct {
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	CommitteeID uuid.UUID `json:"committee_id"`
}

func (q *Queries) CreatePosition(ctx context.Context, arg CreatePositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, createPosition, arg.Name, arg.Email, arg.CommitteeID)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Active,
		&i.CommitteeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPosition = `-- name: GetPosition :one
SELECT id, name, email, active, committee_id, created_at, updated_at, deleted_at FROM position
WHERE ID = $1 LIMIT 1
`

func (q *Queries) GetPosition(ctx context.Context, id uuid.UUID) (Position, error) {
	row := q.db.QueryRowContext(ctx, getPosition, id)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Active,
		&i.CommitteeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPositions = `-- name: ListPositions :many
SELECT id, name, email, active, committee_id, created_at, updated_at, deleted_at FROM position
ORDER BY name
`

func (q *Queries) ListPositions(ctx context.Context) ([]Position, error) {
	rows, err := q.db.QueryContext(ctx, listPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Position
	for rows.Next() {
		var i Position
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Active,
			&i.CommitteeID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePosition = `-- name: UpdatePosition :one
UPDATE position
    SET name = $2,
    email = $3,
    committee_id = $4
WHERE ID = $1
RETURNING id, name, email, active, committee_id, created_at, updated_at, deleted_at
`

type UpdatePositionParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	CommitteeID uuid.UUID `json:"committee_id"`
}

func (q *Queries) UpdatePosition(ctx context.Context, arg UpdatePositionParams) (Position, error) {
	row := q.db.QueryRowContext(ctx, updatePosition,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.CommitteeID,
	)
	var i Position
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Active,
		&i.CommitteeID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
